### PR TITLE
Update to latest lb controller helm release

### PR DESCRIPTION
**Pull request by niroz89**

### CODE REVIEW

**Comment by niroz89** [comment]
@lawliet89 marking it as draft first and let me test with bt-drupal.

Guoyou encountered this error: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2495

**Comment by lawliet89** [comment]
@niroz89 is this still relevant?

**Comment by niroz89** [comment]
yes relevant, current default version wont work with eks 1.22, havent tested yet. let me test today and make it ready.

**Comment by niroz89** [comment]
Values are updated part of #4 , we will expose variables when needed.

**Pull request closed without merging**
